### ISSUE TITLE
new discord update

### ISSUE THREAD

**Issue by hakerman69420** [FlashAL/Nocturnal-discord-theme#6]
for me the newest discord update broke the theme where the server list is

**Comment by FlashAL** [comment]
the theme is working and updated for the latest public version of the discord. at least I have not received versions newer than Stable 80314 (649cbaf) yet.
1. try to reinstall discord.
2. try to reinstall BeterDiscord.
3. the problem may have occurred due to bugs in third party plugins so try disabling them if you are using them.
